// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXkXIKxcSMAhNwxUyb3W3i5mQCtDIn1gY',
    appId: '1:23962399848:web:f4d8237077408ef47fb7dd',
    messagingSenderId: '23962399848',
    projectId: 'ecotrack-f6155',
    authDomain: 'ecotrack-f6155.firebaseapp.com',
    storageBucket: 'ecotrack-f6155.firebasestorage.app',
    measurementId: 'G-KZ0T8699ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9_YAxAAqfa7M19YFQg63fR_sP4NeBVc',
    appId: '1:23962399848:android:db99ff38ccac97f77fb7dd',
    messagingSenderId: '23962399848',
    projectId: 'ecotrack-f6155',
    storageBucket: 'ecotrack-f6155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3eIJa13XH59V6_vH6_exok0YE1RaWhj8',
    appId: '1:23962399848:ios:60a1dcb0151ecba27fb7dd',
    messagingSenderId: '23962399848',
    projectId: 'ecotrack-f6155',
    storageBucket: 'ecotrack-f6155.firebasestorage.app',
    androidClientId: '23962399848-3hp4maij3v0v0s68a7lfoq88rtknjmj8.apps.googleusercontent.com',
    iosClientId: '23962399848-b06ck6589j0c97ic7kacm8e6qp3g83r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3eIJa13XH59V6_vH6_exok0YE1RaWhj8',
    appId: '1:23962399848:ios:60a1dcb0151ecba27fb7dd',
    messagingSenderId: '23962399848',
    projectId: 'ecotrack-f6155',
    storageBucket: 'ecotrack-f6155.firebasestorage.app',
    androidClientId: '23962399848-3hp4maij3v0v0s68a7lfoq88rtknjmj8.apps.googleusercontent.com',
    iosClientId: '23962399848-b06ck6589j0c97ic7kacm8e6qp3g83r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXkXIKxcSMAhNwxUyb3W3i5mQCtDIn1gY',
    appId: '1:23962399848:web:3fc4cfff430fb4d87fb7dd',
    messagingSenderId: '23962399848',
    projectId: 'ecotrack-f6155',
    authDomain: 'ecotrack-f6155.firebaseapp.com',
    storageBucket: 'ecotrack-f6155.firebasestorage.app',
    measurementId: 'G-WV6QFJEELV',
  );

}